### ISSUE TITLE
Project name suggestions

### ISSUE THREAD

**Issue by stax76** [mpvnet-player/mpv.net-experimental#1]
Finding a good name isn't easy, possible alternatives for mpv-gui are mpv-ne (newbie edition) or mpv-bi (batteries included).

**Comment by SatL1Ng** [comment]
Hmmm

mpv+ or mpv-plus 

mpv-eui (enhance user interface) or e-MPV or MPV-E

**Comment by versedwildcat** [comment]
While this is of course subjective, MPV-NG or xMPV sounds  best to me.

**Comment by stax76** [comment]
Thanks for the suggestions.

It would be possible to keep the mpv.net name, one issue with that is that there are people that don't like .NET and C#, maybe because it is from Microsoft, a large cooperation in general or maybe because it's not as fast as C/C++/Rust, could be many reasons.

Keeping the mpv.net repo with all the issues and ratings would make sense, suddenly having a different name and lots of changes would cause some friction.

Some religious people would not like EVO.

Ideally, I think it should be easy to remember and type, and avoid possible negative associations.

**Comment by ruulr** [comment]
stampv
First 3 letters of your username + mpv.

**Comment by TheBestPessimist** [comment]
Yeah, would it be hubris if you'd name it mpv-stax-gui ?

**Comment by stax76** [comment]
I recently changed my mind and decided to keep the name mpv.net.
