### ISSUE TITLE
Please add the command panel again

### ISSUE THREAD

**Issue by dyphire** [mpvnet-player/mpv.net-experimental#6]
Due to mpv cannot switch the language IME when typing on Windows, alternative implementations through scripts only support search for latin character.

**Comment by stax76** [comment]
That's unfortunate, maybe it can be fixed, it's not a topic I know much.

If it cannot be solved, I can add it back.

**Comment by dyphire** [comment]
> That's unfortunate, maybe it can be fixed, it's not a topic I know much.
> 
> If it cannot be solved, I can add it back.

mpv related issues: https://github.com/mpv-player/mpv/issues/9168

**Comment by stax76** [comment]
I tried adding the command palette, the code does not work, and I don't understand why. Either I missed something or Microsoft changed something.

Windows has special IME related window messages, previously these were not forwarded to mpv, I changed it to forward the messages to mpv, but I don't know if it helps to use IME mode with the Lua scripts.
