### ISSUE TITLE
`Show Config Editor` command not work

### ISSUE THREAD

**Issue by dyphire** [mpvnet-player/mpv.net-experimental#7]
Using the master branch to build tests, this `Show Config Editor` command cannot take effect.

**Comment by stax76** [comment]
It seems I had changed code without testing it, it's now fixed.

I stopped developing in this repo and moved all the code from this repo to the original mpv.net repo, once the issues in this repo are addressed, I achieve this repo.

https://github.com/mpvnet-player/mpv.net/commits/main
