### ISSUE TITLE
Add native support for `thumbfast` script

### ISSUE THREAD

**Issue by dyphire** [mpvnet-player/mpv.net-experimental#9]
Enable mpvnet to natively support thumbnail generation using thumbfast scripts without relying on mpv programs, just like ImpPlay. ref https://github.com/po5/thumbfast?tab=readme-ov-file#mpv-frontends

**Comment by stax76** [comment]
There is an [encoding request](https://github.com/mpvnet-player/mpv.net/issues/387) by @hooke007, it was labeled with priority low, I changed this not to priority medium, and I changed the issue title.
